"""
Audit logging service for tracking all agent actions
"""
import uuid
from typing import Optional, Dict, Any
from datetime import datetime
from sqlalchemy.orm import Session
from loguru import logger

from app.models.audit_log import AuditLog
from app.db.session import SessionLocal


class AuditService:
    """Service for logging agent actions and commands to audit_logs table"""
    
    @staticmethod
    async def log_command(
        user_id: uuid.UUID,
        command_text: str,
        action_json: Optional[Dict[str, Any]] = None,
        result: str = "pending",
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> uuid.UUID:
        """
        Log a voice command and its action plan
        
        Args:
            user_id: The user who issued the command
            command_text: The transcribed voice command
            action_json: The action plan generated by LLM
            result: Execution result (pending, success, failed, etc.)
            session_id: WebSocket session ID
            metadata: Additional context (confidence, latency, etc.)
        
        Returns:
            The audit log entry ID
        """
        db = SessionLocal()
        try:
            full_action = {
                "plan": action_json,
                "session_id": session_id,
                "metadata": metadata or {},
                "timestamp": datetime.utcnow().isoformat(),
            }
            
            audit_entry = AuditLog(
                id=uuid.uuid4(),
                user_id=user_id,
                command_text=command_text[:1024],  # Truncate if too long
                action_json=full_action,
                result=result,
            )
            db.add(audit_entry)
            db.commit()
            
            logger.info(
                f"Audit log created: user={user_id}, command='{command_text[:50]}...', "
                f"result={result}, id={audit_entry.id}"
            )
            
            return audit_entry.id
            
        except Exception as e:
            logger.error(f"Failed to create audit log: {e}")
            db.rollback()
            raise
        finally:
            db.close()
    
    @staticmethod
    async def update_result(
        audit_id: uuid.UUID,
        result: str,
        error: Optional[str] = None,
        execution_time_ms: Optional[int] = None,
    ):
        """
        Update the result of an audit log entry
        
        Args:
            audit_id: The audit log entry to update
            result: New result status (success, failed, cancelled, etc.)
            error: Error message if failed
            execution_time_ms: Total execution time
        """
        db = SessionLocal()
        try:
            entry = db.query(AuditLog).filter(AuditLog.id == audit_id).first()
            if entry:
                entry.result = result
                
                # Update metadata in action_json
                if entry.action_json:
                    entry.action_json = {
                        **entry.action_json,
                        "final_result": result,
                        "error": error,
                        "execution_time_ms": execution_time_ms,
                        "completed_at": datetime.utcnow().isoformat(),
                    }
                
                db.commit()
                logger.debug(f"Audit log updated: id={audit_id}, result={result}")
        except Exception as e:
            logger.error(f"Failed to update audit log: {e}")
            db.rollback()
        finally:
            db.close()
    
    @staticmethod
    async def log_agent_action(
        user_id: uuid.UUID,
        action_type: str,
        action_details: Dict[str, Any],
        result: str = "success",
    ):
        """
        Log individual agent actions (navigation, form fill, etc.)
        
        Args:
            user_id: The user performing the action
            action_type: Type of action (navigate, fill, click, speak)
            action_details: Details of the action
            result: Action result
        """
        db = SessionLocal()
        try:
            audit_entry = AuditLog(
                id=uuid.uuid4(),
                user_id=user_id,
                command_text=f"[AGENT_ACTION] {action_type}",
                action_json={
                    "type": action_type,
                    "details": action_details,
                    "timestamp": datetime.utcnow().isoformat(),
                },
                result=result,
            )
            db.add(audit_entry)
            db.commit()
            
        except Exception as e:
            logger.error(f"Failed to log agent action: {e}")
            db.rollback()
        finally:
            db.close()


# Singleton instance
audit_service = AuditService()
